import uuid
from datetime import datetime
from typing import List, Optional

from sqlalchemy import (
    BigInteger,
    Computed,
    DateTime,
    ForeignKey,
    Numeric,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class PackingList(Base):
    """One physical packing run."""

    __tablename__ = "packing_lists"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # Human-readable reference. seq comes from a sequence so two lists created
    # at the same moment cannot collide; reference is generated from it in
    # Postgres so the two can never drift apart.
    seq: Mapped[Optional[int]] = mapped_column(
        BigInteger, server_default=text("nextval('packing_lists_seq')")
    )
    reference: Mapped[Optional[str]] = mapped_column(
        Text, Computed("'PL' || lpad(seq::text, 4, '0')", persisted=True)
    )

    # Packing classification (Plums, Fruits, ...). Deliberately separate from
    # products.category, which is the POS pricing category and means something
    # else entirely.
    category: Mapped[Optional[str]] = mapped_column(Text)

    created_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_users.id")
    )
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")

    # now(), not timezone('Asia/Manila', now()): the latter yields a naive
    # Manila wall-clock reading that a TIMESTAMPTZ column then mislabels as UTC,
    # putting every row 8 hours into the future. Store the instant; let clients
    # render it in local time.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    items: Mapped[List["PackingItem"]] = relationship(
        "PackingItem",
        back_populates="packing_list",
        cascade="all, delete-orphan",
        order_by="PackingItem.created_at",
    )


class PackingItem(Base):
    """One product on a packing list."""

    __tablename__ = "packing_items"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    packing_list_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("packing_lists.id", ondelete="CASCADE"),
        nullable=False,
    )
    product_id: Mapped[str] = mapped_column(
        String(24), ForeignKey("products.id"), nullable=False
    )

    # 'packs' -> quantity is a pack count; 'grams' -> quantity is raw grams.
    unit: Mapped[str] = mapped_column(Text, nullable=False)
    quantity: Mapped[float] = mapped_column(Numeric, nullable=False)

    # Copied from products.pack_weight_g when the row is added, never live-read:
    # pack sizes change, and an old list must keep the weights it was packed at.
    pack_weight_g_snapshot: Mapped[Optional[float]] = mapped_column(Numeric)

    # Generated by Postgres. Computed() marks them read-only so SQLAlchemy never
    # tries to write them, which keeps the arithmetic entirely server-side.
    total_kg: Mapped[Optional[float]] = mapped_column(
        Numeric,
        Computed(
            "CASE WHEN unit = 'packs' "
            "THEN quantity * pack_weight_g_snapshot / 1000 "
            "ELSE quantity / 1000 END",
            persisted=True,
        ),
    )
    total_packs: Mapped[Optional[float]] = mapped_column(
        Numeric,
        Computed(
            "CASE WHEN unit = 'packs' THEN quantity "
            "ELSE FLOOR(quantity / NULLIF(pack_weight_g_snapshot, 0)) END",
            persisted=True,
        ),
    )

    # Filled in after the physical packing, from the printed sheet.
    actual_packed: Mapped[Optional[float]] = mapped_column(Numeric)
    remarks: Mapped[Optional[str]] = mapped_column(Text)

    # now(), not timezone('Asia/Manila', now()): the latter yields a naive
    # Manila wall-clock reading that a TIMESTAMPTZ column then mislabels as UTC,
    # putting every row 8 hours into the future. Store the instant; let clients
    # render it in local time.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    packing_list: Mapped["PackingList"] = relationship(
        "PackingList", back_populates="items"
    )
