-- ===========================================================================
-- SUPERSEDED — DO NOT RUN.
--
-- An earlier revision shifted packing timestamps by -8 hours to convert them
-- into true UTC instants. That was the wrong call and has been reverted.
--
-- Every table in this schema stores the Manila wall-clock reading, via
--     created_at TIMESTAMPTZ DEFAULT timezone('Asia/Manila', now())
--
-- The value is tagged UTC by the column type but is not a UTC instant. That is
-- a real inconsistency, but converting only packing_lists and packing_items
-- would have made them the only tables in the database working that way —
-- 8 hours apart from products and transactions on any join, silently.
--
-- The display bug it was chasing is fixed on the frontend instead: see
-- formatDateTime in frontend/src/services/packingApi.ts, which renders these
-- values without converting zones.
--
-- If this file was already run, put the affected rows back with:
--
--     UPDATE packing_lists SET created_at = created_at + INTERVAL '8 hours';
--     UPDATE packing_items SET created_at = created_at + INTERVAL '8 hours';
--
-- Only if it was run, and only once. Check first — a row whose created_at is
-- well behind the current Manila wall clock is the sign it was shifted:
--
--     SELECT reference, created_at, timezone('Asia/Manila', now()) AS manila_now
--     FROM packing_lists ORDER BY seq;
-- ===========================================================================
