"""Initial database schema with products, stores, transactions, transaction_items, and inventory tables

Revision ID: 60a8995b51cf
Revises: 
Create Date: 2025-10-20 16:09:44.169624

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60a8995b51cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_examples')
    op.alter_column('inventory', 'product_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('inventory', 'store_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('inventory', 'quantity_on_hand',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('inventory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_inventory_product_id'), table_name='inventory')
    op.drop_index(op.f('idx_inventory_store_id'), table_name='inventory')
    op.create_index('idx_product_store', 'inventory', ['product_id', 'store_id'], unique=False)
    op.create_index('idx_store_product', 'inventory', ['store_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_store_id'), 'inventory', ['store_id'], unique=False)
    op.alter_column('products', 'id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('products', 'sku',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('products', 'barcode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('products', 'price_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('products', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'track_stock_level',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'is_parent_product',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.drop_index(op.f('idx_products_name'), table_name='products')
    op.drop_index(op.f('idx_products_sku'), table_name='products')
    op.drop_index(op.f('products_embedding_idx'), table_name='products', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.drop_column('products', 'embedding')
    op.alter_column('stores', 'id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('stores', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('stores', 'address1',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('stores', 'address2',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('stores', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('stores', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('stores', 'country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('stores', 'postal_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('stores', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('stores', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('stores', 'website',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_stores_name'), table_name='stores')
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.alter_column('transaction_items', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transaction_items', 'transaction_ref_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('transaction_items', 'product_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('transaction_items', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('transaction_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('transaction_items', 'item_total',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('transaction_items', 'item_subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('transaction_items', 'discount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('transaction_items', 'tax',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('transaction_items', 'tax_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('transaction_items', 'item_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('transaction_items', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('transaction_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_transaction_items_product_id'), table_name='transaction_items')
    op.drop_index(op.f('idx_transaction_items_transaction_ref_id'), table_name='transaction_items')
    op.create_index('idx_product_transaction', 'transaction_items', ['product_id', 'transaction_ref_id'], unique=False)
    op.create_index(op.f('ix_transaction_items_id'), 'transaction_items', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_items_product_id'), 'transaction_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_transaction_items_transaction_ref_id'), 'transaction_items', ['transaction_ref_id'], unique=False)
    op.drop_constraint(op.f('transaction_items_product_id_fkey'), 'transaction_items', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transaction_items', 'promotions')
    op.drop_column('transaction_items', 'selected_options')
    op.alter_column('transactions', 'ref_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('transactions', 'invoice_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('transactions', 'store_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('transactions', 'register_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('transactions', 'employee_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('transactions', 'customer_ref_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('transactions', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'sub_total',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'discount',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'tax',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'rounded_amount',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'service_charge',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('transactions', 'cancelled_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('transactions', 'comment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('transactions', 'return_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('transactions', 'sale_invoice_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('transactions', 'channel',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('transactions', 'table_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_transactions_customer_ref_id'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_invoice_number'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_store_id'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_time'), table_name='transactions')
    op.create_index('idx_transaction_time_store', 'transactions', ['transaction_time', 'store_id'], unique=False)
    op.create_index('idx_transaction_type_time', 'transactions', ['transaction_type', 'transaction_time'], unique=False)
    op.create_index(op.f('ix_transactions_employee_id'), 'transactions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_transactions_invoice_number'), 'transactions', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_transactions_is_cancelled'), 'transactions', ['is_cancelled'], unique=False)
    op.create_index(op.f('ix_transactions_ref_id'), 'transactions', ['ref_id'], unique=False)
    op.create_index(op.f('ix_transactions_store_id'), 'transactions', ['store_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_time'), 'transactions', ['transaction_time'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.drop_constraint(op.f('transactions_store_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transactions', 'payments')
    op.drop_column('transactions', 'pickup_information')
    op.drop_column('transactions', 'delivery_information')
    op.drop_column('transactions', 'contact_detail')
    op.drop_column('transactions', 'promotions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('promotions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('contact_detail', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('delivery_information', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('pickup_information', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('payments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_store_id_fkey'), 'transactions', 'stores', ['store_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_time'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_store_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ref_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_cancelled'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_invoice_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_employee_id'), table_name='transactions')
    op.drop_index('idx_transaction_type_time', table_name='transactions')
    op.drop_index('idx_transaction_time_store', table_name='transactions')
    op.create_index(op.f('idx_transactions_time'), 'transactions', ['transaction_time'], unique=False)
    op.create_index(op.f('idx_transactions_store_id'), 'transactions', ['store_id'], unique=False)
    op.create_index(op.f('idx_transactions_invoice_number'), 'transactions', ['invoice_number'], unique=False)
    op.create_index(op.f('idx_transactions_customer_ref_id'), 'transactions', ['customer_ref_id'], unique=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'table_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'channel',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'sale_invoice_number',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'return_reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'comment',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'cancelled_by',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('transactions', 'service_charge',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'rounded_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'tax',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'discount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'sub_total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('transactions', 'customer_ref_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'employee_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'register_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transactions', 'invoice_number',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'ref_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('transaction_items', sa.Column('selected_options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('transaction_items', sa.Column('promotions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction_items', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_items_product_id_fkey'), 'transaction_items', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_transaction_items_transaction_ref_id'), table_name='transaction_items')
    op.drop_index(op.f('ix_transaction_items_product_id'), table_name='transaction_items')
    op.drop_index(op.f('ix_transaction_items_id'), table_name='transaction_items')
    op.drop_index('idx_product_transaction', table_name='transaction_items')
    op.create_index(op.f('idx_transaction_items_transaction_ref_id'), 'transaction_items', ['transaction_ref_id'], unique=False)
    op.create_index(op.f('idx_transaction_items_product_id'), 'transaction_items', ['product_id'], unique=False)
    op.alter_column('transaction_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction_items', 'notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transaction_items', 'item_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transaction_items', 'tax_code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transaction_items', 'tax',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('transaction_items', 'discount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('transaction_items', 'item_subtotal',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    op.alter_column('transaction_items', 'item_total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    op.alter_column('transaction_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('transaction_items', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('transaction_items', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('transaction_items', 'transaction_ref_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transaction_items', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.create_index(op.f('idx_stores_name'), 'stores', ['name'], unique=False)
    op.alter_column('stores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stores', 'website',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'postal_code',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'country',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'state',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'city',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'address2',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'address1',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('stores', 'id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('products', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index(op.f('products_embedding_idx'), 'products', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('idx_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('idx_products_category'), 'products', ['category'], unique=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'is_parent_product',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'track_stock_level',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('products', 'unit_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('products', 'price_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'barcode',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'sku',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_inventory_store_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_index('idx_store_product', table_name='inventory')
    op.drop_index('idx_product_store', table_name='inventory')
    op.create_index(op.f('idx_inventory_store_id'), 'inventory', ['store_id'], unique=False)
    op.create_index(op.f('idx_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.alter_column('inventory', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory', 'quantity_on_hand',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('inventory', 'store_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('inventory', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('training_examples',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sql', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), server_default=sa.text("'correct'::text"), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('training_examples_pkey'))
    )
    # ### end Alembic commands ###
