"""
Propose a product -> supplier mapping from purchase history, for a person to approve.

WHY THIS EXISTS. Nothing in the business records who supplies a product: there
is no supplier column on `products` and no supplier master. The only evidence is
what was bought from whom before, and it reaches 650 of 3,723 products. Every
purchasing question is therefore answered over a fraction of the range, and
`get_purchase_plan` has to say so on every result.

WHAT THIS SCRIPT DOES, AND WHAT IT REFUSES TO DO. It reads purchase history and
writes `definitions/product_suppliers.yaml` with `status: proposed`. It decides
nothing: a product bought from exactly one supplier is proposed with that
supplier, a product bought from several is listed as ambiguous with all of them
and no choice made, and a product with no purchase history is simply absent.

NOTHING READS THE FILE UNTIL A PERSON APPROVES IT. Tools use the mapping only
when `status: approved`, which a human sets by editing the file and committing
it. That is the same shape as the workflow promotion gate: proposed by machine,
proved against real evidence, made permanent by a person. Until then
`get_purchase_plan` behaves exactly as it did.

NOT RUN AUTOMATICALLY, and never by the agent against production without being
asked. Run it yourself:

    python ops/propose_supplier_map.py            # writes the proposal
    python ops/propose_supplier_map.py --check    # reports drift, writes nothing

It connects with DATABASE_URL because it reads purchase history to PROPOSE a
definition, which is a maintenance job rather than something George does.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import sys
from collections import defaultdict
from datetime import date

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "definitions" / "product_suppliers.yaml"

QUERY = """
SELECT l.product_id,
       p.sku,
       p.name                              AS product,
       o.supplier_name                     AS supplier,
       COUNT(DISTINCT o.id)                AS orders,
       MAX(o.created_at_source)::date      AS last_ordered,
       SUM(l.ordered_qty)                  AS units_ordered
FROM purchase_order_lines l
JOIN purchase_orders o ON o.id = l.purchase_order_id
LEFT JOIN products p    ON p.id = l.product_id
WHERE l.product_id IS NOT NULL
  AND o.supplier_name IS NOT NULL
GROUP BY 1, 2, 3, 4
ORDER BY 3, 4
"""


def q(text: str | None) -> str:
    """A YAML double-quoted scalar. Supplier and product names contain anything."""
    if text is None:
        return '""'
    return '"' + str(text).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report what would change and write nothing")
    args = ap.parse_args()

    url = os.environ.get("DATABASE_URL")
    if not url:
        env = ROOT / "backend" / ".env"
        if env.exists():
            for line in env.read_text(encoding="utf-8").splitlines():
                if line.startswith("DATABASE_URL="):
                    url = line.split("=", 1)[1].strip().strip('"').strip("'")
                    break
    if not url:
        print("DATABASE_URL is not set.", file=sys.stderr)
        return 1

    import psycopg
    from psycopg.rows import dict_row

    dsn = re.sub(r"^postgresql\+\w+://", "postgresql://", url)
    with psycopg.connect(dsn, autocommit=True) as conn:
        with conn.cursor(row_factory=dict_row) as cur:
            cur.execute("SET TRANSACTION READ ONLY")
            cur.execute(QUERY)
            rows = [dict(r) for r in cur.fetchall()]
            cur.execute("SELECT COUNT(*) AS n FROM products")
            all_products = cur.fetchone()["n"]

    by_product: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_product[r["product_id"]].append(r)

    confident = {pid: v[0] for pid, v in by_product.items() if len(v) == 1}
    ambiguous = {pid: v for pid, v in by_product.items() if len(v) > 1}

    print(f"products in catalogue      : {all_products:,}")
    print(f"products with any history  : {len(by_product):,}")
    print(f"  exactly one supplier     : {len(confident):,}  -> proposed")
    print(f"  more than one supplier   : {len(ambiguous):,}  -> left for a person")
    if args.check:
        print("\n--check: nothing written.")
        return 0

    out: list[str] = []
    w = out.append
    w("# =============================================================================")
    w("# PRODUCT -> SUPPLIER, proposed from purchase history.")
    w("#")
    w("# GENERATED BY ops/propose_supplier_map.py. Do not hand-edit the `confident`")
    w("# block to fix a mistake in it: correct the purchase history, or move the")
    w("# entry into `overrides` below, which the generator never touches.")
    w("#")
    w("# NOTHING READS THIS FILE UNTIL `status` IS `approved`. Set it by hand, after")
    w("# reading it. Until then get_purchase_plan works from purchase history")
    w("# directly, exactly as before, and says that it is doing so.")
    w("#")
    w("# WHY A FILE AND NOT A TABLE. This is a DEFINITION — who supplies what — and")
    w("# definitions live in files that a person reviews and git records. The review")
    w("# is the gate, the diff is the audit trail, and approving it is a commit.")
    w("# =============================================================================")
    w(f"version: 1")
    w(f"generated: {q(date.today().isoformat())}")
    w("generated_by: ops/propose_supplier_map.py")
    w("derived_from: \"purchase_order_lines.product_id -> purchase_orders.supplier_name\"")
    w("")
    w("# proposed | approved. A person sets this, never the generator and never George.")
    w("status: proposed")
    w("approved_by: null")
    w("approved_at: null")
    w("")
    w("measured:")
    w(f"  products_in_catalogue: {all_products}")
    w(f"  products_with_history: {len(by_product)}")
    w(f"  proposed: {len(confident)}")
    w(f"  ambiguous: {len(ambiguous)}")
    w("")
    w("# ---------------------------------------------------------------------------")
    w("# Corrections a person has made. Read INSTEAD of anything below for the same")
    w("# product id, and never overwritten by the generator. This is where a product")
    w("# with no purchase history, or one the history gets wrong, is given its real")
    w("# supplier.")
    w("# ---------------------------------------------------------------------------")
    w("overrides: {}")
    w("")
    w("# ---------------------------------------------------------------------------")
    w("# Bought from exactly one supplier. Proposed, not established.")
    w("# ---------------------------------------------------------------------------")
    w("confident:")
    for pid in sorted(confident, key=lambda k: (confident[k]["product"] or "").lower()):
        r = confident[pid]
        w(f"  {q(pid)}:")
        w(f"    supplier: {q(r['supplier'])}")
        w(f"    sku: {q(r['sku'])}")
        w(f"    product: {q(r['product'])}")
        w(f"    orders: {r['orders']}")
        w(f"    last_ordered: {q(str(r['last_ordered']) if r['last_ordered'] else None)}")
    w("")
    w("# ---------------------------------------------------------------------------")
    w("# Bought from MORE THAN ONE supplier. No choice is made here — a product can")
    w("# genuinely have two sources, and picking the most recent or the largest")
    w("# would be inventing a sourcing decision. Move the right answer into")
    w("# `overrides` above, or leave it and the product stays out of every plan.")
    w("# ---------------------------------------------------------------------------")
    w("ambiguous:")
    for pid in sorted(ambiguous, key=lambda k: (ambiguous[k][0]["product"] or "").lower()):
        rs = sorted(ambiguous[pid], key=lambda r: (-r["orders"], r["supplier"]))
        w(f"  {q(pid)}:")
        w(f"    sku: {q(rs[0]['sku'])}")
        w(f"    product: {q(rs[0]['product'])}")
        w("    suppliers:")
        for r in rs:
            w(f"      - name: {q(r['supplier'])}")
            w(f"        orders: {r['orders']}")
            w(f"        last_ordered: {q(str(r['last_ordered']) if r['last_ordered'] else None)}")
    w("")

    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"\nwrote {OUT.relative_to(ROOT)}  ({len(out):,} lines, status: proposed)")
    print("Review it, set `status: approved`, and commit. Nothing reads it before that.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
